# Generated by Django 3.2.2 on 2023-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('status', models.CharField(choices=[('available', 'available'), ('busy', 'busy')], default='available', max_length=10)),
                ('open', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevators', models.ManyToManyField(related_name='elevators', to='api.Elevator')),
            ],
        ),
    ]
