# Generated by Django 3.2.2 on 2023-07-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='open',
            new_name='is_open',
        ),
    ]
