# Generated by Django 3.2.2 on 2023-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_open_elevator_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='next_destination',
            field=models.PositiveIntegerField(default=0, verbose_name='next'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('busy', 'busy'), ('under_maintainance', 'under_maintainance')], default='available', max_length=20),
        ),
    ]
