# Generated by Django 3.2.2 on 2023-07-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230727_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='next_destination',
            field=models.IntegerField(default=-1, verbose_name='next'),
        ),
    ]
